# -*- coding: utf-8 -*-
"""ML PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1XnQmJ3O-vKpNIioG9wGe4XvfIm0DXZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 110

df = pd.read_csv("ecommerce_customer_behavior.csv")
print(df.shape)
df.head()

df.info()
df.isna().sum()

num_cols = ["purchase_frequency", "avg_order_value", "browsing_time_minutes",
            "session_count", "discount_usage_rate", "cart_abandonment_rate",
            "days_since_last_purchase"]
cat_cols = ["preferred_device", "preferred_category"]

for c in num_cols:
    df[c] = df[c].fillna(df[c].median())

df[num_cols].isna().sum()

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
for ax, col in zip(axes.flat, num_cols[:6]):
    sns.histplot(df[col], kde=True, ax=ax, color="#2E5EAA")
    ax.set_title(col)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
sns.heatmap(df[num_cols].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
df["preferred_device"].value_counts().plot(kind="bar", ax=axes[0], color="#3D8BFF")
axes[0].set_title("Device Preference")
df["preferred_category"].value_counts().plot(kind="bar", ax=axes[1], color="#1B2A4A")
axes[1].set_title("Category Preference")
plt.tight_layout()
plt.show()

encoder = OneHotEncoder(sparse_output=False, drop="first")
cat_encoded = encoder.fit_transform(df[cat_cols])
cat_encoded_df = pd.DataFrame(cat_encoded, columns=encoder.get_feature_names_out(cat_cols))

features = pd.concat([df[num_cols].reset_index(drop=True), cat_encoded_df], axis=1)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)
X_scaled.shape

pca_full = PCA().fit(X_scaled)
explained = pca_full.explained_variance_ratio_

plt.figure(figsize=(7, 5))
plt.plot(np.arange(1, len(explained) + 1), np.cumsum(explained), marker="o", color="#2E5EAA")
plt.axhline(0.9, color="gray", linestyle="--", linewidth=1)
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("PCA — Explained Variance")
plt.show()

n_components = int(np.argmax(np.cumsum(explained) >= 0.90) + 1)
print("Components needed for 90% variance:", n_components)

pca = PCA(n_components=n_components, random_state=42)
X_pca = pca.fit_transform(X_scaled)

pca2 = PCA(n_components=2, random_state=42)
X_pca2 = pca2.fit_transform(X_scaled)

plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_pca2[:, 0], y=X_pca2[:, 1], s=25, alpha=0.7, color="#2E5EAA")
plt.title("PCA (2D) — Linear Projection")
plt.xlabel("PC1"); plt.ylabel("PC2")
plt.show()

tsne = TSNE(n_components=2, perplexity=35, learning_rate="auto", init="pca", random_state=42)
X_tsne = tsne.fit_transform(X_pca)

scores = {}
for k in range(2, 7):
    km = KMeans(n_clusters=k, random_state=42, n_init=10).fit(X_pca)
    scores[k] = silhouette_score(X_pca, km.labels_)
scores

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10).fit(X_pca)
df["cluster"] = kmeans.labels_
print("Silhouette score:", silhouette_score(X_pca, kmeans.labels_))

plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_tsne[:, 0], y=X_tsne[:, 1], hue=df["cluster"].astype(str),
                palette="tab10", s=28, alpha=0.85)
plt.title("t-SNE (2D) — Customer Clusters")
plt.xlabel("t-SNE dim 1"); plt.ylabel("t-SNE dim 2")
plt.legend(title="Cluster")
plt.show()

profile = df.groupby("cluster")[num_cols].mean().round(2)
profile["count"] = df.groupby("cluster").size()
profile

# IMPORTANT: cluster numbers can come out in a different order each run.
# Look at Cell 16's table and match each cluster ID to a label based on its actual values:
# - highest purchase_frequency, low days_since_last_purchase -> Frequent Buyer
# - highest avg_order_value, low discount_usage_rate -> High-Value Customer
# - highest discount_usage_rate -> Discount-Driven Shopper
# - highest cart_abandonment_rate, highest days_since_last_purchase -> Occasional Browser

label_map = {
    0: "Frequent Buyer",
    1: "High-Value Customer",
    2: "Discount-Driven Shopper",
    3: "Occasional Browser",
}
df["cluster_label"] = df["cluster"].map(label_map)
df["cluster_label"].value_counts()

df.to_csv("ecommerce_customer_behavior_with_clusters.csv", index=False)
from google.colab import files
files.download("ecommerce_customer_behavior_with_clusters.csv")